### ISSUE TITLE
Support TimescaleDb

### ISSUE THREAD

**Issue by alexferreira** [kubedb/project#195]
Hi guys, I need to use timescaledb along with kubedb, any prediction to have that possibility in kuedb?

**Comment by tamalsaha** [comment]
Can you tell us more about it ?

**Comment by alexferreira** [comment]
I currently use kubedb in production here at the company I work for manages postgres and redis. We also use influxdb as timeseries. but doing several tests I saw that timescaledb would supply much better than we need because we could use the postgres trigger to feed the reports. without counting that we will have a better performance and less a bank to maintain since timescale is a database based on postgres and that is also a timeseries. then the change would be less painful.

references:
https://www.timescale.com/

https://blog.dnsfilter.com/3-billion-time-series-data-points-dnsfilter-replaced-influxdb-with-timescaledb-d9f827702f8b

**Comment by LinAnt** [comment]
We also use timescale DB, I do not think this is a specific thing KubeDB should support. A better approach would be to make it easier to let the users run custom postgres images, in which the user can install any add on / plug-in they desire. 

There are 2 PR's that are waiting to get merged at the moment. One which gives the user power to specify image to use, and another one that makes it easier to configure your postgres containers.

**Comment by tamalsaha** [comment]
Here is the new proposal for supporting extensions

https://github.com/kubedb/project/issues/183#issuecomment-409715800

**Comment by tamalsaha** [comment]
We have created a new repository to host TimescaleDB docker images https://github.com/kubedb/timescale

@annymsMthd has added an example Dockerfile https://github.com/kubedb/cli/blob/master/docs/guides/postgres/custom-versions/setup.md

Contributions are welcome for Dockerfiles. :)

**Comment by cloud-rocket** [comment]
Is it planned to be officially released? Tnx

**Comment by gboor** [comment]
I'm running timescale on kubedb with a custom image and can issue a pull request for the Dockerfile we have. However, looking at the kubedb/postgres repo, it seems there is a LOT more to it than just a Dockerfile. Where can I find instructions on setting up this repo properly? Or can I just submit a simple Dockerfile, since the operator and all that are already in the kubedb/postgres base image?

**Comment by pocorschi** [comment]
@gboor  - Can you share your Dockerfile somewhere? would be great to take a look at it. I'm also running a custom image version following some instructions found somewhere and it works great but it has a couple of breaking flaws: 

- if you run it with a custom databaseSecret.secretName it will create your user for you but that user cannot create databases nor can it administer roles
- if you run it with the standard auth you cannot login into it since the postgres user gets created without a password it seems

> Connection matched pg_hba.conf line 97: "host  all         all         0.0.0.0/0       md5"
2019-08-16 09:11:15.984 UTC [164] FATAL:  password authentication failed for user "postgres"
2019-08-16 09:11:15.984 UTC [164] DETAIL:  User "postgres" has no password assigned.

**Comment by gboor** [comment]
@pocorschi a colleague of mine released 2 images on docker hub that are KubeDB compatible;

https://hub.docker.com/r/iamliamc/timescaledb
https://hub.docker.com/r/iamliamc/timescaledb-postgis

The latter one includes both timescale and postgis extensions.

I know that these images work for our setup, but I have not tested them extensively.

**Comment by pocorschi** [comment]
@gboor thank you, I'll take a look at them.

**Comment by tamalsaha** [comment]
This issue has been resolved in KubeDB release v2021.03.17 . Please open a new bug if you still see this issue.
