### ISSUE TITLE
elasticsearch.yml that is used to spin up cluster should used as configmap?

### ISSUE THREAD

**Issue by virtuman** [kubedb/project#207]
Shouldn't elasticsearch.yml be inserted and volumemounted as configmap? it seems to make a lot more sense to expose it from configmap to be able to further manipulate the cluster behavior?

**Comment by hossainemruz** [comment]
@virtuman we are already working on that. We are going to support providing custom configuration for all KubeDB supported databases. We have already completed this for all other databases. Currently working on Elasticsearch. This will be available in next release.

We are tracking this issue here: https://github.com/kubedb/project/issues/187
Related issue: https://github.com/kubedb/project/issues/193

**Comment by tamalsaha** [comment]
Dup https://github.com/kubedb/project/issues/193
