### ISSUE TITLE
How can I specify a storage class with the installation of KubeDB using Helm?

### ISSUE THREAD

**Issue by patsevanton** [kubedb/project#324]
Hello!
How can I specify a storage class with the installation of KubeDB using Helm?

**Comment by hossainemruz** [comment]
@patsevanton  you don't have to specify storage class while install KubeDB.  You have to specify it while creating database crd through `spec.storageclass` field.

**Comment by patsevanton** [comment]
I want install KubeDB like this
`helm install incubator/elasticsearch --name my-release --set data.storageClass=local-storage,data.storage=10Gi`

**Comment by hossainemruz** [comment]
@patsevanton you can't do that. KubeDB does not work that way. When you install KubeDB it only install the operator and it's related resources. No database is created. In order to create database, you have to create a database crd.
https://kubedb.com/docs/0.9.0-rc.0/guides/elasticsearch/quickstart/quickstart/

**Comment by tamalsaha** [comment]
@patsevanton , we don't provide a chart for the `Elasticsearch` crd like `incubator/elasticsearch` .You can create your custom chart based the yaml examples we have in the docs and use that chart.

**Comment by tamalsaha** [comment]
We have not currently published charts for individual database types. It is
not clear to me how far we should go with the values file for this type of
chart.

Regards,
-Tamal

**Comment by tamalsaha** [comment]
Dup https://github.com/kubedb/project/issues/439
