### ISSUE TITLE
Don't inherit labels from CRD into offshoots?

### ISSUE THREAD

**Issue by tamalsaha** [kubedb/project#370]
https://kubernetes.slack.com/archives/C8149MREV/p1545221308253500

**Comment by paveq** [comment]
Making it possible to modify this behaviour is important in scenarios where K8S objects are managed by external entity such as ArgoCD. Such tools usually use labels to find resources they need to manage, including removal.

In my case ArgoCD manages CRD from KubeDB itself, and that works fine. However since statefulset created by the KubeDB controller inherits labels from CRD, ArgoCD thinks it should remove the statefulset, as ArgoCD has no knowledge that the resource should exists.

In this case we want statefulset managed by KubeDB, not ArgoCD. That should happen when the resources don't inherit label **applications.argoproj.io/app-name** (or in case of newer ArgoCD, it's using **app.kubernetes.io/instance**).

**Comment by tamalsaha** [comment]
I understand the issue but I am not sure what is the answer here. Here are a list of things to consider:

1. The current behavior is desired by some users. It answers the user req: "I want to find all resources that are related to this DB crd".

2. The general question for ArgoCD project is are they "misusing" labels? If ArgoCD operator are to "control/manage" some resource, then it should presumably be an "owner" for that resource with [controller=true](https://github.com/kubernetes/apimachinery/blob/master/pkg/apis/meta/v1/controller_ref.go#L23).

3. If you provide a way to turn of this feature, here are some options:
  - Make it a boolean flag at the operator level to stop propagating any labels.
  - Make it a list of keys flag (eg, --blacklisted-label-keys=app.kubernetes.io/instance) to operator so that it does not propagate those flags.
  - This could be some per CRD based "flag" (spec.avoidPropagatingLabels = ["app.kubernetes.io/instance"]. I think this is the most invasive and probably not acceptable solution.

Two things need to happen before we can reach an answer:

- Find out why argo project is not using controller ref. @paveq, do you want to ask in their issue queue?
- What is the purpose of this new key `app.kubernetes.io/instance` and whether this is used correctly from Argo project?

**Comment by jessesuen** [comment]
> What is the purpose of this new key app.kubernetes.io/instance and whether this is used correctly from Argo project?

The sole purpose of this label, is for Argo CD to track what resources comprise an "application." I confirmed with sig-apps that we are using the label properly based on https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/.

The label is also used for pruning purposes. An Argo CD sync is semantically equivalent to:
```
kubectl apply -f some/directory --prune -l -l app.kubernetes.io/instance=my-application
```

> Find out why argo project is not using controller ref. 

Argo CD doesn't own/control resources in the same way that a deployment owns a replicaset which owns the pods, because Argo CD works across clusters. The best way to think of Argo CD, is as a glorified `kubectl apply`, because in the end we are just literally running `kubectl apply` to deploy resources to clusters, including external ones. Since we apply across clusters, it doesn't seem proper to set an ownership reference to a resource in a completely different cluster.

**Comment by paveq** [comment]
Thanks for clarification from agroCD point of view @jessesuen 

I'm wondering if there exists third alternative that will satisfy both requirements:
- "I want to find all resources that are related to this DB crd"
- AgroCD needs to be able to differentiate using labels resources it needs to control/purge

In K8S common labels is there label named **app.kubernetes.io/managed-by**. Would it make sense for both projects set this label to their own? And for ArgoCD to check both managed-by and instance labels? That way we still have loglcal mapping of application instance, but different pieces are just managed by different mechanims.

**Comment by jessesuen** [comment]
> Would it make any sense for both projects set this label to their own, and for ArgoCD to check both labels when reconciliating resources? 

This won't fully solve the problem. It's currently possible for a user to customize the label key that get's injected (i.e. it doesn't have to be `app.kubernetes.io/instance`). We make the default `app.kubernetes.io/instance`, but it can be changed to `random.label.key.io/appname`. As long as KubeDB is carrying over the all labels to the StatefulSet, Argo CD will not know how to differentiate the objects that it created vs. the ones that KubeDB carried over.

I forgot to add that controller ref is not an option for us because there's no efficient way to query the kubernetes API for resources based on a controller ref.

To be honest, I feel the implicit behavior to carry over *all* labels of the top level CRD object into the offshoots, is surprising behavior. Especially if there's no mechanism to disable this. For example, all of the k8s built-in types including Deployment, Stateful, Job, etc..., use a separate `spec.template.metadata` field to control labels in their offshoots. i.e.

```yaml
spec:
  template:
    metadata:
      labels:
        foo: bar
```

> The current behavior is desired by some users. It answers the user req: "I want to find all resources that are related to this DB crd".

I agree that a valid need & use case, but I feel there are other ways to accomplish this that won't cause
interoperability problems to not just Argo CD, but things like the [Application CRD](https://github.com/kubernetes-sigs/application), which promotes the use of labels on resources associated with the concept of an "application". 

Some suggestions:
1. injection using a label specific to the project, e.g. the name the KubeDB CRD instance `kubed.appscode.com/name: foo`
2. Introduce a `spec.template.metadata` into the KubeDB spec.

**Comment by paveq** [comment]
I think "Make it a boolean flag at the operator level to stop propagating any labels" would be best the option to implement now, and would fix the immediate issue. Later on this can be improved to some of the directions above.

@tamalsaha How do you feel about that solution?

**Comment by tamalsaha** [comment]
I have made 2 changes:

- KubeDB operator will apply the follow labels to its offshots based on database CRD.
  - app.kubernetes.io/name
  - app.kubernetes.io/version
  - app.kubernetes.io/instance
  - app.kubernetes.io/component
  - app.kubernetes.io/managed-by

- The following labels keys will *NOT* be propagated from CRD to its offshoots 
  - app.kubernetes.io/name
  - app.kubernetes.io/version
  - app.kubernetes.io/instance
  - app.kubernetes.io/managed-by

- KubeDB operator will propagate the following keys from db CRD to its offshoots
  - app.kubernetes.io/part-of
  - app.kubernetes.io/component

**Comment by tamalsaha** [comment]
This change will be part of the next release (hopefully this week). Please leave a comment if this issue is not resolved yet.

**Comment by tamalsaha** [comment]
@paveq , 0.11.0 has been released. This issue should be fixed now. Please let me know if this issue persists.
