### ISSUE TITLE
Admission webhook denies wal-g support for GCS

### ISSUE THREAD

**Issue by iamrz1** [kubedb/project#401]
While trying to create a postgres object with GCS as spec.archiver.storage, I am receiving the following error message:
 ```
Error from server (Forbidden): error when creating "pg_with_wal_g.yaml": admission webhook "postgres.validators.kubedb.com" denied the request: no storage provider is configured.
```
This is possibly a result of only s3 being hard coded here:
https://github.com/kubedb/postgres/blob/aa9766b79f62ddc7c2bec658b7c9d831305de95d/pkg/admission/validator.go#L180-L185
Additionally, GCS has been explicitly mentioned to be not supported.

**Comment by harbesc** [comment]
Would you all be willing to accept PRs for this issue? We are switching to GKE and would like WAL support.

**Comment by the-redback** [comment]
Hi @harbesc,
We welcome any contribution from user end. Feel free to submit a PR. ^_^ 

We maintain wal-g fork [here](https://github.com/kubedb/wal-g), so that we can build alpine image of wal-g. Other than that, it is even with wal-g repository. 

The wal-g binary is up-to-date. we need to update the docker file, postgres operator codebase and E2E test to verify everything is working. 

Let me know if you face any difficulty.

**Comment by the-redback** [comment]
@harbesc , Are you working on it? Any update on work? Otherwise, I can work on it. :)

**Comment by harbesc** [comment]
@the-redback I am not working on it, we would probably have to incorporate it into our sprint planning. Thanks for taking it on.
