### ISSUE TITLE
Push the latest Docker images for Mongo and Elasticsearch

### ISSUE THREAD

**Issue by sherifkayad** [kubedb/project#416]
Hello guys,

The latest images for Elasticsearch and Mongo are not pushed to the docker public registry. Could you please push them?

The latest tag for mongo is 3.4 (https://hub.docker.com/r/kubedb/mongo/tags)

The latest tag for elasticsearch is 6.4 (https://hub.docker.com/r/kubedb/elasticsearch/tags)

**Comment by the-redback** [comment]
We tend to push the docker images only when we release a new version. Otherwise, it will make problem in user's machine. But you can build the docker images on your own from here. https://github.com/kubedb/mongodb/tree/master/hack/docker/mongo

Set docker registry,
```
export DOCKER_REGISTRY=<docker-registry>
```

Then, run `make.sh build` `make.sh push` in each version.

**Comment by sherifkayad** [comment]
@the-redback thanks for that solution .. however, I am not sure what you meant by it will break the user's machine.

I mean if we build all the images from the latest master branch and push them with their different tags, then why should this be a problem? specially with these that don't even exist so far.

Maybe you can explain more?

**Comment by botzill** [comment]
I agree with @sherifkayad. This is the only thing that is missing so far ib kubedb, to have latest images for dbs. I understand that it's not easy to keep uptodate, but this will be a big step if you able to do it.

**Comment by sherifkayad** [comment]
Stale
