### ISSUE TITLE
MongoDB - automatically add new users with specific roles

### ISSUE THREAD

**Issue by botzill** [kubedb/project#421]
Hi.

I tried to create an init script where I create a new user:
```
use admin
db.createUser({...})
```

All seems to be setup OK, it's starts but seems that this init script is not working, is this the right way to do it?

Thx!

**Comment by the-redback** [comment]
what is your file extension? `.sh` or .`js`? I faced difficulty too, turns out the script I was trying, is not pure bash or `js` script. I think your problem is similar. 

My working js script is https://github.com/kubedb/mongodb-init-scripts/blob/master/init.js 

If you are using `.sh` extension, try using `mongo` cli in bash. https://stackoverflow.com/a/6000360/4628962

**Comment by botzill** [comment]
Hi.

I did change to:

```
use db_name;
db.createUser({"user":"<user_name>", "pwd":"<pass_here>","roles": [{"role": "dbAdmin", "db": "<db_name>"}]});
```

But still not creating it.

Note that `db_name` does not exists, but this should not be an issue as db names in mondo a dynamic.

**Comment by the-redback** [comment]
I recreated this. The below srcipt worked.

```
db = db.getSiblingDB('db_name');
db.createUser({"user":"root", "pwd":"password","roles": [{"role": "dbAdmin", "db": "db_name"}]});
```

Can you verify?

**Comment by botzill** [comment]
Hi @the-redback 

Yes, seems to work now, thx! I was using `use db_name` and maybe this is not a valid `.js` file.

**Comment by the-redback** [comment]
Yes. Glad it worked. :)
