### ISSUE TITLE
Postgres: Leader election values do not match spec; cause panic

### ISSUE THREAD

**Issue by JustinHead** [kubedb/project#437]
The defined spec for leader election configuration of retry does not match the set default. Also, the current default actually causes a panic in the operator with the message `panic: renewDeadline must be greater than retryPeriod*JitterFactor`.

Changing the default to the spec of `2` fixes the issue.

Spec:
https://github.com/kubedb/apimachinery/blob/master/api/crds/postgres.yaml#L9348-L9353

Code:
https://github.com/kubedb/postgres/blob/master/pkg/leader_election/leader_election.go#L176-L179

Panic:
```
panic: renewDeadline must be greater than retryPeriod*JitterFactor
goroutine 70 [running]:
github.com/kubedb/postgres/vendor/k8s.io/client-go/tools/leaderelection.RunOrDie(0x3b73de0, 0xc000052088, 0x3b7dd00, 0xc00024ad80, 0x37e11d600, 0x2540be400, 0x37e11d600, 0x21b52e8, 0x21b52f0, 0xc000a57180)
    /go/src/github.com/kubedb/postgres/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:164 +0xa8
github.com/kubedb/postgres/pkg/leader_election.RunLeaderElection.func1(0xc00024ad80, 0xf, 0xa, 0xf, 0xc000476100, 0xc00005004a, 0xb, 0xc0005d80a0, 0xb, 0xc0005d8090, ...)
    /go/src/github.com/kubedb/postgres/pkg/leader_election/leader_election.go:87 +0x1dd
created by github.com/kubedb/postgres/pkg/leader_election.RunLeaderElection
    /go/src/github.com/kubedb/postgres/pkg/leader_election/leader_election.go:86 +0x7dc
```

**Comment by the-redback** [comment]
Hi @JustinHead 

Can you provide your sample CRD, so that we can recreate? Also, how you installed kubedb operator? 

Have you provided all the three values of `LeaderElection` spec? When, user is defining LeaderElection, he/she needs to provide all three.

Also, the panic is expected behavior when the leaderelection specs doesn't match the client-go validation. But, KubeDB should have given error before creating the statefulset.

**Comment by the-redback** [comment]
I can verify the problem. 
TO recreate the problem: 1. Run operator without webhook. 2. Create CRD without leaderelection given.
